#! /bin/sh

# -----------------------------------------------
# Autostart

killall picom
sleep 0.5
picom &

killall sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

killall polybar
polybar &

killall flashfocus
flashfocus &


killall dunst
dunst &

feh --bg-scale  ~/.dotfiles/bspwm/MOTD/wallpapers/bg1.jpg
setxkbmap es

# -----------------------------------------------
# Workspaces / monitors

bspc monitor -d 1 2 3 4 5 6
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# -----------------------------------------------
# Padding

bspc config top_padding 10
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

# -----------------------------------------------
# windows

bspc config split_ratio 0.50
bspc config window_gap 40
bspc config border_width 0
bspc config normal_border_color "#dddd"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#ffffff"
bspc config presel_feedback_color "#355B81"
bspc config urgent_border_color "#dd2727"

# -----------------------------------------------
# Monocle

bspc config single_monocle true
bspc config gapless_monocle false
bspc config borderless_monocle false

# -----------------------------------------------
# Mouse

bspc config focus_follows_pointer true


# -----------------------------------------------
# Notification

notify-send "Bspwm status:  " &

# -----------------------------------------------
