#! /bin/sh

#! /bin/sh

# -----------------------------------------------

# Autostart
killall picom
sleep 0.1
picom &
sleep 0.1

killall polybar
sleep 0.2
polybar &

kitty -e fish -c "fastfetch; exec fish" &  

killall dunst
sleep 0.2
dunst &

feh --bg-scale  ~/.dotfiles/Nord/wallpapers/wallpaper6.jpg
setxkbmap es 
pgrep -x sxhkd > /dev/null || sxhkd &

# -----------------------------------------------

# Workspaces / monitors
bspc monitor -d 1 2 3 4 5 6

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# -----------------------------------------------

# Padding
bspc config top_padding 10
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

# -----------------------------------------------

# windows
bspc config split_ratio 0.50
bspc config window_gap 40
bspc config border_width 1
bspc config normal_border_color "#00FFFFFF"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#8fbcbb"
bspc config presel_feedback_color "#355B81"
bspc config urgent_border_color "#dd2727"

# -----------------------------------------------

# Monocle
bspc config single_monocle true
bspc config gapless_monocle false    # equivalent of i3 smart gaps, which only applies gaps if theres more than 1 window
bspc config borderless_monocle false # border for when there is only 1 window (monocle)

# -----------------------------------------------

# Mouse
bspc config focus_follows_pointer true


# -----------------------------------------------

# Notification
notify-send "Bspwm status:  " &
